{"record_info": {"total_time": "0:46:06", "start_time": "14:50:39", "steps": 816}, "trace_info": {"trace_count": 4, "traces_type": ["TRACEBACK", "TRACEBACK", "TRACEBACK"], "traces": [" Traceback (most recent call last):\n   File \"gameinit.py\", line 101, in setup_cython", " Traceback (most recent call last):\n   File \"entities\\client\\helper\\ElkLogger.py\", line 39, in elklog\n   File \"lib\\json\\__init__.py\", line 231, in dumps\n   File \"lib\\json\\encoder.py\", line 201, in encode\n   File \"lib\\json\\encoder.py\", line 264, in iterencode\n   File \"lib\\json\\encoder.py\", line 178, in default", " ============= TRACEBACK =============\n File \"entities\\client\\patch\\new_patch\\patch_mgr.py\", in update\n  > 1931: N/A\n \t                 tb : <traceback object at 0xb698ce90>\n \t              value : MyException('VersionStage: get version info error. 2028\\nNone\\n',)\n \t               type : <class 'patch.new_patch.patch_mgr.MyException'>\n \t            md5_msg : 'VersionStage: get version info error. 2028\\nNone\\n'\n \t                  e : MyException('VersionStage: get version info error. 2028\\nNone\\n',)\n \t      next_stage_id : 5\n \t               args : (0.065998002886772156, 0.13329213857650757, 0.23341020941734314, 0.43291711807250977)\n \t               self : <patch.new_patch.patch_mgr.PatchMgr object at 0xc0633ff0>\n File \"entities\\client\\patch\\new_patch\\patch_mgr.py\", in updateStage_check_md5_1\n  > 861: N/A\n \t               info : 2028\n \t              state : 1\n \t      versionResult : (1, 2028)\n \t               self : <patch.new_patch.patch_mgr.VersionStage object at 0xb698a0f0>\n MyException\n  > VersionStage: get version info error. 2028\n None\n \n ============= END ============="], "traces_count": [1, 2, 1]}}
